export const ADD_TASK_TIMER = "ADD_TASK_TIMER";
export const DELETE_TASK_TIMER = "DELETE_TASK_TIMER";
export const SET_TIMERS = "SET_TIMERS";
export const SET_DELETED_TIMERS = "SET_DELETED_TIMERS";
export const PAUSE_TIMER = "PAUSE_TIMER";
export const RESUME_TIMER = "RESUME_TIMER";
export const DESTROY_DELETED_TIMER = "DESTROY_DELETED_TIMER";
